"""`tripwire next-key` — atomic sequential key allocation.

Thin CLI wrapper around `core.key_allocator.allocate_keys`. The atomicity
guarantee (file lock on `project.yaml`) lives in the allocator; this
module is just argument parsing, error reporting, and stdout formatting.

The agent calls this once per entity it intends to create, reads the
allocated key(s) from stdout, and then writes the entity file directly
with the corresponding `id:` frontmatter field. UUIDs are generated by
the agent itself — no CLI round-trip for those.
"""

from __future__ import annotations

from pathlib import Path

import click

from tripwire.core.key_allocator import (
    KeyAllocationError,
    allocate_keys,
)


@click.command(name="next-key")
@click.option(
    "--project-dir",
    type=click.Path(path_type=Path, file_okay=False, dir_okay=True),
    default=".",
    show_default=True,
    help="Path to the project root (contains project.yaml).",
)
@click.option(
    "--type",
    "key_type",
    type=click.Choice(["issue", "session"]),
    default="issue",
    show_default=True,
    help="Which counter to increment.",
)
@click.option(
    "--count",
    type=click.IntRange(min=1, max=1000),
    default=1,
    show_default=True,
    help=(
        "How many keys to allocate in a single atomic operation. "
        "Capped at 1000 to guard against runaway agents."
    ),
)
def next_key_cmd(project_dir: Path, key_type: str, count: int) -> None:
    """Atomically allocate the next sequential key(s) for this project.

    Prints one key per line to stdout. The counter in `project.yaml` is
    incremented under a file lock, so concurrent invocations are safe.

    \b
    Examples:
        tripwire next-key              # → TST-42
        tripwire next-key --count 3    # → TST-43\\nTST-44\\nTST-45
        tripwire next-key --type session
    """
    try:
        keys = allocate_keys(
            project_dir.expanduser().resolve(),
            key_type,  # type: ignore[arg-type]
            count=count,
        )
    except KeyAllocationError as exc:
        raise click.ClickException(str(exc)) from exc

    for key in keys:
        click.echo(key)
